---
# tasks file for selinux

- name: ensure selinux and libselinux-python are installed
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - selinux-policy
    - libselinux-python
  tags:
    - selinux

- name: ensure selinux is configured
  selinux:
    state: "{{ selinux_state }}"
    policy: "{{ selinux_policy }}"
  tags:
    - selinux

